### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by tomasbm07** [coolbro3/Kahoot-Bot#3]
After executing, i get this error message:

---

Kahoot spammer v 1.4.4
Please enter a game pin:13512
Please enter a name:bob
Please enter a amount of bots to join(Default is 50):20
Starting chrome...
C:\Users\tomas\Desktop\Kahoot-Bot-master\Kahoot bot.py:23: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=chrome_options)

DevTools listening on ws://127.0.0.1:65511/devtools/browser/6f2674a6-50bf-4f89-b9b0-5f95beb91ac2
Navigating to Kahoot...
Traceback (most recent call last):
  File "C:\Users\tomas\Desktop\Kahoot-Bot-master\Kahoot bot.py", line 77, in <module>
    bot()
  File "C:\Users\tomas\Desktop\Kahoot-Bot-master\Kahoot bot.py", line 52, in bot
    element = wait.until(EC.element_to_be_clickable((By.ID, 'inputSession')))
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

----
I dont know if im using the right version of chromedriver and dont know if thats the reason why I get this error. Can you please help?

**Comment by OwenCochell** [comment]
So, to start, I am currently working on a newer, better version of this Kahoot bot that will not only be able to spam games, but will also be able to answer questions correctly. It will also interact directly with the Kahoot API, which can be done by using urllib(included in the Python standard library), which removes the need for selenium and other complicated dependencies. I will keep this version of the bot up until I officially release the new and improved version here on my GitHub page, which will likely be in a new repository. So keep an eye out! Just a suggestion, if you "watch" my GitHub account, you can configure the settings so you receive an email whenever their is new activity on my account, so you can be informed upon the new release of the bot, which will be better in almost every conceivable way from this one!

So, about your error...

It appears that the Selenium API has changed greatly, apparently one of the developer options I am using for chrome-driver are deprecated? It also appears that Kahoot changed their page layout, so the script is telling Selenium to look for elements that do not exist/aren't rendering fast enough, which is, again, a design flaw of this Kahoot bot and a reason why I am ruling out Selenium in the next iteration of this bot.

I unfortunately will be, again, deprecating this bot in the near future, so I will probably not be fixing this problem. Again, a newer, better version of this bot will be released here in a future date, so bear with me while I continue to develop it.

Thanks for reading!
